# Generated by Django 4.1.4 on 2022-12-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0003_alter_student_address_alter_student_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="phone", new_name="phone_number",
        ),
    ]
